on:
  push:
    branches: [ main ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Do a git checkout including submodules
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: fail
          
      - name: Build
        run: cd src/ && hugo
          
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: src/public/
          remote_path: /var/www/green-galliard.com/bay/blog/
          remote_host: bay.green-gaillard.com
          remote_user: agni
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
