on:
  push:
    branches: [ main ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: fail
      - name: Push
        run: hugo && rsync -avz --delete public/ agni@167.71.175.126:/var/www/green-gaillard.com/bay/blog/
